### ISSUE TITLE
Very slow animations with Swift on iPad

### ISSUE THREAD

**Issue by DevAlloy** [zhxnlai/ZLSwipeableView#16]
How to reproduce:
- Create empty project
- Import lib via bridge header
- Write CardView class from demo with Swift
- Put ZLSwipeableView as in demo project

I noticed that behaviour only on iPad, but O-C project works smoothly, and if I use smaller cards(100x200 for example) it works fine too.
Do you think that It is because of bridging? If so, I'll try to rewrite lib on Swift.

**Comment by qbraksa** [comment]
I'm also having slow animations on the iPhone 6 Plus simulator when testing the demo project.

I added `shouldRasterize` to the `cardView` view, but didn't seem to solve the issue. 

```objc
- (UIView *)nextViewForSwipeableView:(ZLSwipeableView *)swipeableView {
    if (self.colorIndex >= self.colors.count) {
        self.colorIndex = 0;
    }

    CardView *view = [[CardView alloc] initWithFrame:swipeableView.bounds];
    view.backgroundColor = [self colorForName:self.colors[self.colorIndex]];
    self.colorIndex++;
    
    view.layer.shouldRasterize = YES;

...
```
