### ISSUE TITLE
Neatly stacked tiles?

### ISSUE THREAD

**Issue by komocode** [zhxnlai/ZLSwipeableView#18]
Would be nice if we can have a "sloppiness" float variable where 0.0 would have neatly stacked cards while 1.0 would have completely sloppy stacked tiles.

**Comment by zhxnlai** [comment]
Do you mean something like this?
~~~objective-c
/// Enable this to rotate the views behind the top view. Default to `YES`.
@property (nonatomic) BOOL isRotationEnabled;
~~~

**Comment by komocode** [comment]
Yep! Though it would be nice if it showed that it more cards instead of directly stacking on top of each other. 
![Image of Tinder](http://i.imgur.com/hyTfgbM.jpg)
