### ISSUE TITLE
Add option to disable swiping left/right

### ISSUE THREAD

**Issue by krzd** [zhxnlai/ZLSwipeableView#19]
Would be great to have an option to prevent users to swipe left or right.

**Comment by zhxnlai** [comment]
Thanks, I just added a new property for that:
~~~objective-c
/// Enable this to allow swiping left or right. Default to `YES`.
@property (nonatomic) BOOL isSwipingEnabled;
~~~

**Comment by krzd** [comment]
@zhxnlai Awesome, although this actually enables you to disable swiping for left AND right, not left OR right. In my application, I want to be able to let users only swipe left, but not right.

**Comment by zhxnlai** [comment]
I changed it to 
~~~objective-c
/// Enable this to allow swiping left or right. Default to
/// `ZLSwipeableViewDirectionBoth`.
@property (nonatomic) ZLSwipeableViewDirection direction;
~~~

**Comment by Shrutimittal91** [comment]
Hi, i kept

> swipeableView.allowedDirection = ZLSwipeableViewDirectionHorizontal;

But still cards are moving up and down on swipe. How to restrict that.
