### ISSUE TITLE
Swiping not working

### ISSUE THREAD

**Issue by mikecastro26** [zhxnlai/ZLSwipeableView#20]
Hi, I downloaded the demo project to test it, but I don't seem to be able to swipe left or right. The only way to do so is by touching the buttons "Swipe left" and "Swipe right", not by dragging it. Any help with that?

Thank you!

**Comment by zhxnlai** [comment]
I just updated the demo app. Could you try out the latest version and see if it works? Also, are you running the demo app on device or simulator? What are the version numbers for Xcode, iOS SDK and device's OS?

**Comment by mikecastro26** [comment]
Hey there

It is working on the current version! thank you! 

I'm running the demo app in the simulator, Xcode 6, iOS 7.1 and iPhone 5s.

**Comment by zhxnlai** [comment]
Thanks!
