### ISSUE TITLE
A way to get the current top view

### ISSUE THREAD

**Issue by mergesort** [zhxnlai/ZLSwipeableView#29]
Is there a way in the API to get the current top view? I'm trying to do a custom transition involving the top view, and would ideally not have to keep a cache and state of what is the current top view for when I animate the view controller's pop.

If it doesn't already exist, it could either through a property of the ZLSwipeableView, or through a delegate method, like `swipeableView:didSwipeView:inDirection:` becoming `swipeableView:didSwipeView:topView:inDirection:`, or adding another delegate method like `swipeableView:didMoveViewToTop:`

If any of these (or another idea) sound good to you, I'd be happy to add a PR.

Thanks!

**Comment by zhxnlai** [comment]
Thanks for asking!

The method `swipeableView:didSwipeView:inDirection:` gives you the view that has been swiped. Does the `topView:` parameter in `swipeableView:didSwipeView:topView:inDirection:` mean the view that is showing up (going to be the top view)?

**Comment by zhxnlai** [comment]
There is also a private method `(UIView *)topSwipeableView`. Do you think it would be helpful to add it to the public interface?

**Comment by mergesort** [comment]
@zhxnlai I think that would be helpful. I started using `swipeableViews.subviews.lastObject` like you were, but it's probably the best idea to expose that publicly.
