### ISSUE TITLE
Prevent view from escaping in specific direction(s)

### ISSUE THREAD

**Issue by oferRounds** [zhxnlai/ZLSwipeableView#30]
For example, I would like to allow user to swipe the view in all possible directions, but allow it to escape only when the direction is left or right.

I do see the "direction" property, but from what I understand its goal is not that.
Is there a way to do it?

Thanks for the great project!

**Comment by zhxnlai** [comment]
Hi, the latest master branch actually allows you to set the direction using enum. It is not published to cocoapod yet but you can download the source code and add to your project.

~~~objective-c
typedef NS_ENUM(NSUInteger, ZLSwipeableViewDirection) {
    ZLSwipeableViewDirectionNone = 0,
    ZLSwipeableViewDirectionLeft,
    ZLSwipeableViewDirectionRight,
	ZLSwipeableViewDirectionHorizontal = ZLSwipeableViewDirectionLeft |
	ZLSwipeableViewDirectionRight,
	ZLSwipeableViewDirectionUp,
	ZLSwipeableViewDirectionDown,
	ZLSwipeableViewDirectionVertical = ZLSwipeableViewDirectionUp |
	ZLSwipeableViewDirectionDown,
	ZLSwipeableViewDirectionAll = ZLSwipeableViewDirectionLeft |
	ZLSwipeableViewDirectionRight | ZLSwipeableViewDirectionUp | ZLSwipeableViewDirectionDown,
};
~~~

**Comment by oferRounds** [comment]
Hi, I actually do use it, but I think there might be a problem, because, for example, on the default mode (ZLSwipeableViewDirectionHorizontal), I am still able to swipe the view away on the Down direction (this is in fact the direction I get on the relevant delegate method).

**Comment by ingouackaz** [comment]
@oferRounds  any news ?

I have the same issue ... .

**Comment by oferRounds** [comment]
@ingouackaz, not currently... If I will, I'll post it here or send a PR. Let me know if you come up with something...

**Comment by oferRounds** [comment]
This does not yet solve all cases. I do have a solution for it, and I just tried issue a PR, but I'm getting a permission denied message. I don't have experience with issuing a PR, so perhaps I'm doing something wrong.
Any idea?

Pushing to https://github.com/zhxnlai/ZLSwipeableView.git
remote: Permission to zhxnlai/ZLSwipeableView.git denied to ofer@rounds.com.
fatal: unable to access 'https://github.com/zhxnlai/ZLSwipeableView.git/': The requested URL returned error: 403

**Comment by oferRounds** [comment]
cc: @ingouackaz

**Comment by zhxnlai** [comment]
@oferRounds Thanks for sharing your solution! Here is a guide to issue a PR: https://guides.github.com/activities/contributing-to-open-source/#contributing Hope that it helps!
