### ISSUE TITLE
Disable swipe up andd swipe down.

### ISSUE THREAD

**Issue by nihtin9mk** [zhxnlai/ZLSwipeableView#37]
How to disable swipe up and swipe down.
The swipe action should be there like tinder, but I need the block card disappearing.

**Comment by criosist** [comment]
Set the swipeView.direction to ZLSwipeViewDirectionHorizontal.

**Comment by zhxnlai** [comment]
Hi guys, checkout the swift version of ZLSwipeableView: https://github.com/zhxnlai/ZLSwipeableViewSwift
