### ISSUE TITLE
Rotation support

### ISSUE THREAD

**Issue by guidev** [zhxnlai/ZLSwipeableView#42]
I noticed a strange behaviour: after the device rotates, the frame of the card goes offscreen (see screenshots).
![img_0553](https://cloud.githubusercontent.com/assets/1105813/7458155/82fd9cd6-f292-11e4-8a8a-bcc0cdf60502.jpg)
![img_0552](https://cloud.githubusercontent.com/assets/1105813/7458156/83047984-f292-11e4-8ead-a3175185ec63.jpg)

 
How can this be resolved?

**Comment by zhxnlai** [comment]
Sorry for the late reply. This is because the card views do not support auto layout. You need to resize them as the screen rotates. BTW, check out the swift version of ZLSwipeableView: https://github.com/zhxnlai/ZLSwipeableViewSwift
