### ISSUE TITLE
Support Combinations of ZLSwipeableViewDirection

### ISSUE THREAD

**Issue by emadd** [zhxnlai/ZLSwipeableView#43]
Would be nice if...

```
self.swipeableView.direction = ZLSwipeableViewDirection.Left | ZLSwipeableViewDirection.Up | ZLSwipeableViewDirection.Right
```

**Comment by zhxnlai** [comment]
Hi, I worked on the swift version of ZLSwipeableView over the weekend. It totally supports combination of direction. Check it out: https://github.com/zhxnlai/ZLSwipeableViewSwift
