### ISSUE TITLE
How to control the swipe speed when swiping a view programatically?

### ISSUE THREAD

**Issue by oferRounds** [zhxnlai/ZLSwipeableView#45]
For example, when calling swipeTopViewToUp, make the speed of the swiped away view faster.

**Comment by zhxnlai** [comment]
That is controlled by `pushVelocityMagnitude`

**Comment by oferRounds** [comment]
Thanks @zhxnlai, I have seen it, but from my tests I see that it affects only views which are swiped by the user, and not ones which are swiped programatically.

Any thought?

**Comment by zhxnlai** [comment]
Strangely it is now controlled by `escapeVelocityThreshold`. I will fix it right now.

**Comment by oferRounds** [comment]
Thanks for the very quick response, @zhxnlai - sounds very good! I'll check it tomorrow.

**Comment by oferRounds** [comment]
Works really great - thanks a lot! :)
