### ISSUE TITLE
Support an "Undo" Action 

### ISSUE THREAD

**Issue by oferRounds** [zhxnlai/ZLSwipeableView#46]
This means, for example, when swiping a view away through the right side, the view should be returned from the right.

As for the implementation, I think the best would be if the ZLSwipeableView instance will always save a reference to the last instance which was swiped away, with the direction it was swiped away to. In addition, it will expose an ```undo``` method.

**Comment by zhxnlai** [comment]
Hi, I worked on the swift version of ZLSwipeableView over the weekend. It comes with an [undo example](https://github.com/zhxnlai/ZLSwipeableViewSwift#undo). Check it out: https://github.com/zhxnlai/ZLSwipeableViewSwift

**Comment by oferRounds** [comment]
WTG @zhxnlai and thanks a lot! Looks great!!
I will try it!

**Comment by zhxnlai** [comment]
Thanks!

**Comment by oferRounds** [comment]
Hi @zhxnlai 

It took some time, but I'm now trying to test the new Undo support that you added.
The thing is that I'm not that femiliar with Swift (yet), and I'm having some difficulties doing the replacement of ZLSwipeableView with its Swift veriosn.

How hard do you think it will be to add the Undo support to this Obj-C project? I tried to look, but it doesn't seem trivial to me...

**Comment by cerupcat** [comment]
I'd also love to see this in the obj-c version.
