### ISSUE TITLE
Delegate Not Working

### ISSUE THREAD

**Issue by alexsaidani** [zhxnlai/ZLSwipeableView#47]
I'm having a problem getting the callback functions for swiping right and left to work. 

- (void)swipeableView:(ZLSwipeableView *)swipeableView didSwipeLeft:(UIView *)view
- (void)swipeableView:(ZLSwipeableView *)swipeableView didSwipeRight:(UIView *)view 

I think the setting of the delegate isn't working, but cannot work out why?

**Comment by brewmium** [comment]
Alex,

You are referencing 2 delegates that do not exist. You can see the delegates available in ZLSwipeableViewDemo.h lines 28-50.

The delegate that will do what you want is:

- (void)swipeableView:(ZLSwipeableView *)swipeableView
         didSwipeView:(UIView *)view
          inDirection:(ZLSwipeableViewDirection)direction;
