### ISSUE TITLE
nextViewForSwipeableView not being called with v0.0.8

### ISSUE THREAD

**Issue by yepesasecas** [zhxnlai/ZLSwipeableView#57]
if i install v0.0.8 i don't get nextViewForSwipeableView called.
when i change to v0.0.7 everything works as expected.

v0.0.8 was released 6 days ago.

**Comment by zhxnlai** [comment]
Sorry that I haven't updated the documentation. As a part of the new API design, you need to call loadViewsIfNeeded after setting the data source. Please take a look at https://github.com/zhxnlai/ZLSwipeableView/blob/master/ZLSwipeableViewDemo/ZLSwipeableViewDemo/ZLSwipeableViewController.m

**Comment by yepesasecas** [comment]
@zhxnlai thank you for the fast response. :)
