### ISSUE TITLE
AutoLayout / XIB

### ISSUE THREAD

**Issue by cemkozinoglu** [zhxnlai/ZLSwipeableView#9]
Hey awesome piece of code! Problem... When you load a card from XIB.. and move it around stuff within the card does not stay within the bounds.. hard to explain but let me send a screen show.

**Comment by peacemoon** [comment]
@cemkozinoglu : Can you show me the code how you load the view from xib. I try to do the same thing but have problem while dragging, the image view is not bounded inside the card view (see screenshot)

![screen shot 2015-01-02 at 11 33 07](https://cloud.githubusercontent.com/assets/478757/5595459/9523c5fe-9273-11e4-9f06-0527b706e737.png)

Here are my contraints for my cardview.xib
![screen shot 2015-01-02 at 11 34 41](https://cloud.githubusercontent.com/assets/478757/5595461/a35a735c-9273-11e4-8212-1722b30c777d.png)

**Comment by zhxnlai** [comment]
@peacemoon I just updated the demo app. It now includes an example that loads views from xib.

**Comment by peacemoon** [comment]
@zhxnlai great, thank you

**Comment by yingmu52** [comment]
there are some constrain conflicts, any ideas ? 

*******************
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1758bb90 H:[UIView:0x1759cf90]-(0)-|   (Names: '|':CardView:0x175a34b0 )>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-01-19 00:05:38.493 ZLSwipeableViewDemo[3022:60b] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x17598250 V:|-(0)-[UIView:0x1759cf90]   (Names: '|':CardView:0x175a34b0 )>",
    "<NSLayoutConstraint:0x1758ca70 V:[UIView:0x1759cf90(322)]>",
    "<NSLayoutConstraint:0x175a3aa0 V:[UIView:0x1759cf90]-(0)-|   (Names: '|':CardView:0x175a34b0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x17593d80 h=--& v=--& H:[CardView:0x175a34b0(416.237)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x17574e60 h=--& v=--& V:[CardView:0x175a34b0(410.369)]>"
)

**Comment by zhxnlai** [comment]
@yingmu52 Thanks for reporting this issue! I just fixed it so please try the latest version of the demo app.

**Comment by yingmu52** [comment]
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x14d9ad60 UIButton:0x14d9ac40.width == 4.325*UIButton:0x14d9ac40.height>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-01-21 15:11:25.815 Wish[4909:60b] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x14d98b30 UIImageView:0x14d995a0.width == UIImageView:0x14d995a0.height>",
    "<NSLayoutConstraint:0x14d9a830 UIButton:0x14d9a710.width == 4.325*UIButton:0x14d9a710.height>",
    "<NSLayoutConstraint:0x14d9b360 V:|-(92)-[UIButton:0x14d9af80]   (Names: '|':UIView:0x14d9a680 )>",
    "<NSLayoutConstraint:0x14d9b420 UIButton:0x14d9ac40.height == UIButton:0x14d9af80.height>",
    "<NSLayoutConstraint:0x14d9b480 V:[UIButton:0x14d9af80]-(30)-[UIButton:0x14d9ac40]>",
    "<NSLayoutConstraint:0x14d9b4e0 V:[UIButton:0x14d9ac40]-(30)-[UIButton:0x14d9a710]>",
    "<NSLayoutConstraint:0x14d9b5a0 UIButton:0x14d9a710.height == UIButton:0x14d9ac40.height>",
    "<NSLayoutConstraint:0x14d9b5d0 UIButton:0x14d9a710.width == 0.4325*UIView:0x14d9a680.height>",
    "<NSLayoutConstraint:0x14d9bae0 UIButton:0x14d9a710.bottom == UIImageView:0x14d995a0.bottom>",
    "<NSLayoutConstraint:0x14d9bb10 HomeCardView:0x14d975f0.centerX == UIImageView:0x14d995a0.centerX>",
    "<NSLayoutConstraint:0x14d9bb40 V:|-(8)-[UIImageView:0x14d995a0]   (Names: '|':HomeCardView:0x14d975f0 )>",
    "<NSLayoutConstraint:0x14d9bb70 H:|-(8)-[UIImageView:0x14d995a0]   (Names: '|':HomeCardView:0x14d975f0 )>",
    "<NSLayoutConstraint:0x14d9bc30 V:[UIView:0x14d9a680]-(0)-|   (Names: '|':HomeCardView:0x14d975f0 )>",
    "<NSLayoutConstraint:0x14d9bcc0 V:|-(0)-[UIView:0x14d9a680]   (Names: '|':HomeCardView:0x14d975f0 )>",
    "<NSLayoutConstraint:0x14d97960 H:[HomeCardView:0x14d975f0(304)]>",
    "<NSLayoutConstraint:0x14d99820 V:[HomeCardView:0x14d975f0(422)]>"
)


thanks for updating the library.. unfortunately, I still get some warnings.

**Comment by yingmu52** [comment]
![screen shot 2015-01-21 at 15 14 21](https://cloud.githubusercontent.com/assets/1755380/5847273/3aed3194-a180-11e4-87bb-dfb51e90470c.png)

**Comment by zhxnlai** [comment]
@yingmu52 are you using iOS 8? I double checked and did not get any warning

**Comment by yingmu52** [comment]
![screen shot 2015-01-23 at 12 25 30](https://cloud.githubusercontent.com/assets/1755380/5882091/37418974-a2fb-11e4-8ba5-389ac5ff25fd.png)
![screen shot 2015-01-23 at 12 25 42](https://cloud.githubusercontent.com/assets/1755380/5882090/373e946c-a2fb-11e4-8dcd-65f2fc3afd9a.png)
![screen shot 2015-01-23 at 12 26 56](https://cloud.githubusercontent.com/assets/1755380/5882092/37421772-a2fb-11e4-8d5b-a6acfa275b48.png)


I am running 7.1.2 on my device. .

**Comment by zhxnlai** [comment]
@yingmu52 That's weird, I tested it on both iOS 7 and iOS8 simulator and it worked fine

**Comment by yingmu52** [comment]
https://www.dropbox.com/sh/6r5leuws1p59lyj/AAATZbxFUSXAhABic3HqTdVoa?dl=0


I have put my custom view under this link, it will be great if you could test it for me. thank you :)

**Comment by horseshoe7** [comment]
I have an issue where the swipeable view's frame is changed by auto-layout.  but the card views have been pinned at the size before the swipeableview  frame changed.  Anyone know what I need to do?

**Comment by sun-fox-cj** [comment]
there are some problems while I use this with autolayout in iOS7
